logging:
  level:
    org.axonframework: TRACE

spring:
  datasource:
    url: jdbc:h2:file:~/axondb2;IFEXISTS=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        show_sql: true

